name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift-version: ["6.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Disable Macro Checks
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Build
        run: swift build --verbose

      - name: Run Tests
        run: swift test --verbose

  test-ios:
    name: Test iOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Disable Macro Checks
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: List available iOS simulators
        run: xcrun simctl list devices --json iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme HTTPRequestClient \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -sdk iphonesimulator \
            build

      - name: Test iOS
        run: |
          xcodebuild -scheme HTTPRequestClient \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            -sdk iphonesimulator \
            test

  test-watchos:
    name: Test watchOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Disable Macro Checks
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: List available watchOS simulators
        run: xcrun simctl list devices --json watchOS

      - name: Build for watchOS
        run: |
          xcodebuild -scheme HTTPRequestClient \
            -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=10.5' \
            -sdk watchsimulator \
            build

  test-tvos:
    name: Test tvOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Disable Macro Checks
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Build for tvOS
        run: |
          xcodebuild -scheme HTTPRequestClient \
            -destination 'platform=tvOS Simulator,name=Apple TV,OS=18.2' \
            -sdk appletvsimulator \
            build
